### ISSUE TITLE
signer v3 killing python kernel

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [zksync-sdk/zksync-crypto-c#5]
I am testing the Python SDK of zksync on my laptop, i have been following the guide as shown [Here](https://zksync.io/api/sdk/python/tutorial.html#creating-a-wallet)

when i try to initialize the **signer v3** as shown;  
```
# Initialization from zksync private key
signer_v3 = ZkSyncSigner(library, b"private_key")
```

the jupyter notebook kernel dies and i have to restart the kernel

i have tried to do this multiple times without any success 

please note that in place of ' b"private_key" ' , i use my ethereum wallet private key 

hope this will prove helpful in any possible patches !

**Comment by mutalisk999** [comment]
met the same issue

```
    lib = ZkSyncLibrary(r"./zks_crypto.dll")
    key = bytes.fromhex("a"*64)
    signer = ZkSyncSigner(lib, key)
    print(signer.pubkey_hash().hex())
```

```
thread '<unnamed>' panicked at 'failed to get private key from bytes: NotInField("0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")', zks-crypto-c\src\utils.rs:144:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "D:\zkex-test\zkex-api-test.py", line 29, in <module>
    zk_account()
  File "D:\zkex-test\zkex-api-test.py", line 14, in zk_account
    signer = ZkSyncSigner(lib, key)
  File "C:\Python39\lib\site-packages\zksync_sdk\zksync_signer.py", line 24, in __init__
    self.public_key = self.library.get_public_key(self.private_key)
  File "C:\Python39\lib\site-packages\zksync_sdk\lib.py", line 66, in get_public_key
    self.lib.zks_crypto_private_key_to_public_key(pk, public_key)
OSError: exception: access violation reading 0x0000004369BF0000
```

**Comment by foonsun** [comment]
@mutalisk999 I have met the same issue using zksync-crypto-c example.I try to import the private key not the seed, convert to the key to bytes,then it panics: "panicked at 'failed to get private key from bytes: NotInField("0x94erdfdfdfdfdfddfdfdfdsfdfd") ".
